export const TRIAL_ERROR_CODES = {
	DAILY_LIMIT_REACHED: "TRIAL_DAILY_LIMIT_REACHED",
	QUOTA_CHECK_FAILED: "TRIAL_QUOTA_CHECK_FAILED",
	UPLOAD_FAILED: "TRIAL_UPLOAD_FAILED",
	INVALID_REQUEST: "TRIAL_INVALID_REQUEST",
} as const;

export type TrialErrorCode =
	(typeof TRIAL_ERROR_CODES)[keyof typeof TRIAL_ERROR_CODES];
